# List of behavioural rules used by the detection engine

from Detection.indicators.rules import (
    shadow_delete,
    rapid_files,
    suspicious_extensions,
    file_deletion,
    persistence,
    suspicious_process_spawn,
    unusual_parent_child,
    process_injection,
    process_tampering,
    suspicious_network,
    suspicious_dns,
    rat_beacon,
    rat_scheduled_task,
    rat_named_pipe,
    rat_privileged_access,
    rat_dns_fanout,
    rat_remote_shell,
    rat_uac_bypass,
    rat_host_discovery,
)

DETECTORS = [
    shadow_delete,
    rapid_files,
    suspicious_extensions,
    file_deletion,
    persistence,
    suspicious_process_spawn,
    unusual_parent_child,
    process_injection,
    process_tampering,
    suspicious_network,
    suspicious_dns,
    rat_beacon,
    rat_scheduled_task,
    rat_named_pipe,
    rat_privileged_access,
    rat_dns_fanout,
    rat_remote_shell,
    rat_uac_bypass,
    rat_host_discovery,
]